export const RECOMMENDPRODUCTS_LIST_REQUEST = 'RECOMMENDPRODUCTS_LIST_REQUEST';
export const RECOMMENDPRODUCTS_LIST_SUCCESS = 'RECOMMENDPRODUCTS_LIST_SUCCESS';
export const RECOMMENDPRODUCTS_LIST_FAIL = 'RECOMMENDPRODUCTS_LIST_FAIL';