export const SEARCH_PRODUCT_LIST_REQUEST = "SEARCH_PRODUCT_LIST_REQUEST";
export const SEARCH_PRODUCT_LIST_SUCCESS = "SEARCH_PRODUCT_LIST_SUCCESS";
export const SEARCH_PRODUCT_LIST_FAIL = "SEARCH_PRODUCT_LIST_FAIL";
